// constants.js
module.exports = {
  AUTH_SET_USER: 'auth/SET_USER',
  LOGOUT_CLIENTE: 'LOGOUT_CLIENTE',
  SET_CURRENT_USER : 'SET_CURRENT_USER',

  GET_CLIENTE_REQUEST: 'GET_CLIENTE_REQUEST',
  GET_CLIENTE_SUCCESS: 'GET_CLIENTE_SUCCESS',

  FETCHING_FAILURE: 'FETCHING_FAILURE',

  ADD_FLASH_MESSAGE : 'ADD_FLASH_MESSAGE',
  DELETE_FLASH_MESSAGE :'DELETE_FLASH_MESSAGE'
};
