// constants.js
module.exports = {
  AUTH_SET_USER: 'auth/SET_USER',

  LOGOUT_CLIENTE: 'LOGOUT_CLIENTE',

  GET_CLIENTE_REQUEST: 'GET_CLIENTE_REQUEST',
  GET_CLIENTE_SUCCESS: 'GET_CLIENTE_SUCCESS',

  FETCHING_FAILURE: 'FETCHING_FAILURE',
};