// constants.js
module.exports = {
  AUTH_SET_USER: 'auth/SET_USER',
  LOGOUT_CLIENTE: 'LOGOUT_CLIENTE',

  SET_CURRENT_USER : 'SET_CURRENT_USER',
  LOGOUT_USER : 'LOGOUT_USER',

  GET_CLIENTE_REQUEST: 'GET_CLIENTE_REQUEST',
  GET_CLIENTE_SUCCESS: 'GET_CLIENTE_SUCCESS',

  FETCHING: 'FETCHING',
  FETCHING_FAILURE: 'FETCHING_FAILURE',
  FETCH_SUCESS: 'FETCH_SUCESS',

  ADD_FLASH_MESSAGE : 'ADD_FLASH_MESSAGE',
  DELETE_FLASH_MESSAGE :'DELETE_FLASH_MESSAGE',
  DELETE_ALL_FLASH_MESSAGE: 'DELETE_ALL_FLASH_MESSAGE'
};
